baseurl = "http://kiramclean.com/"
languageCode = "en-CA"
title = "Kira McLean"
canonifyurls = true
PygmentsCodeFences = true
pygmentsstyle = "friendly"

[Params]
  Author = "Kira McLean"
  disqusShortname = "kiramclean"

  DateForm = "Jan 2, 2006"
  Description = "A blog about my journey learning to code and some other things."
  Email = "email@kiramclean.com"
  FaviconFile = "" # TODO:
  GATracker = "XYZ" # TODO:
  GitHub = "//github.com/kiramclean"
  LinkedIn = "//linkedin.com/in/kiramclean"
  Twitter = "//twitter.com/kiraemclean"
